name: push to uffizzi

on:
  push:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '20 */2 * * *'  # 每3小时执行一次

jobs:
  deploy-uffizzi-preview:
    name: Use Remote Workflow to Preview on Uffizzi
    uses: UffizziCloud/preview-action/.github/workflows/reusable.yaml@v2
    with:
      compose-file-cache-key: ''
      compose-file-cache-path: docker-compose.uffizzi.yml
      server: https://app.uffizzi.com
    permissions:
      contents: read
      pull-requests: write
      id-token: write
