name: Build Images and Handle Uffizzi Previews.

on:
  push:
    branches:
      - master
  # pull_request:
  #   types: [opened, reopened, synchronize, closed]

jobs:
  deploy:
    name: Deploy to Uffizzi on Push
    if: ${{ github.event_name == 'push' }}
    uses: UffizziCloud/preview-action/.github/workflows/reusable.yaml@v2
    with:
      compose-file-cache-key: ""
      compose-file-cache-path: docker-compose.uffizzi.yml
      server: https://app.uffizzi.com/
    permissions:
      contents: read
      pull-requests: write
      id-token: write
