name: auto push to uffizzi

on:
  push:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '20 */2 * * *'  # 每3小时执行一次

jobs:
  deploy-uffizzi-preview:
    name: Use Remote Workflow to Preview on Uffizzi
    uses: UffizziCloud/preview-action/.github/workflows/reusable.yaml@v2
    with:
      compose-file-cache-key: '0ad5e9a54f95e41607c714a39e030a63'
      compose-file-cache-path: docker-compose.uffizzi.yml
      server: https://app.uffizzi.com
    permissions:
      contents: read
      pull-requests: write
      id-token: write
